modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="celestial_addition_tetra" #mandatory
version="1.0" #mandatory
displayName="Celestial Addition Tetra" #mandatory
authors="xiaoyue" #optional
description='''${mod_description}'''
[[dependencies.celestial_addition_tetra]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.celestial_addition_tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.celestial_addition_tetra]]
    modId="celestial_core"
    mandatory=true
    versionRange="[1.4.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.celestial_addition_tetra]]
    modId="tetra"
    mandatory=true
    versionRange="[1.20.1-6.4.0,)"
    ordering="AFTER"
    side="BOTH"
